services:
  - type: web
    name: sentinelshield
    env: node
    repo: https://github.com/vitakyrpisit/sentinelshield
    branch: master
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3030
